# Site settings
title: Federico Rossi
description: Portfolio & Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Federico Rossi
user_description: Currently researching about image processing and alternative numerical formats for automotive
user_title: Computer Engineer, PhD Student
email: federico.rossi@ing.unipi.it
# twitter_username: lorem_ipsum
github_username:  federicorossifr
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
